name: Daily Merge Main into Develop

on:
  workflow_dispatch

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into develop
        run: |
          git pull --all
          git checkout develop
          git merge main
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
