name: Daily Merge Main into Develop

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight UTC
  workflow_dispatch:  # This allows the workflow to be trigg

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Main to Develop
        run: |
          echo "Current branch is ${GITHUB_REF##*/}"
          git pull --all
          git checkout develop
          git merge main 

      - name: Create Pull Request from Main to Develop
        run: |
          gh pr create --base develop --head main --title "Daily Merge: Main to Develop" --body "Automated pull request to merge changes from main to develop"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Approve Pull Request
        run: |
          gh pr review --approve --repo ${{ github.repository }} $(gh pr list --base develop --head main --limit 1 --json number --jq '.[0].number')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Push Changes
        run: |
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
