name: Daily Merge Main into Develop

on:
  schedule:
    # This cron job runs every day at midnight UTC
    - cron: '0 0 * * *' 

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into develop
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout develop
          git merge main
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}