name: Daily Merge Main into Develop

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight UTC
  workflow_dispatch:  # This allows the workflow to be trigg

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Main to Develop
        run: |
          echo "Current branch is ${GITHUB_REF##*/}"
          git pull --all
          git checkout develop
          git merge main 
    
      - name: Push Changes
        run: |
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
