name: Daily Merge Main into Develop

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow daily at midnight UTC
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Main to Develop
        run: |
          echo "Current branch is ${GITHUB_REF##*/}"
          git pull --all
          git checkout develop
          git merge main

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Create Pull Request from Main to Develop
        id: create_pr
        run: |
          pr_url=$(gh pr create --title "Daily Merge: Main into Develop" --body "This is an automated pull request to merge changes from main into develop." --head main --base develop --json url --jq '.url')
          echo "Pull request created: $pr_url"
          echo "::set-output name=pr_url::$pr_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  approve_pr:
    runs-on: ubuntu-latest
    needs: create_pr
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Approve Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --base develop --head main --limit 1 --json number --jq '.[0].number')
          gh pr review --approve $pr_number