name: Daily Merge Main into Develop

on:
  schedule:
    - cron: '* * * * *'  # This will run the workflow daily at midnight UTC


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Main to Develop
        run: |
          echo "Current branch is ${GITHUB_REF##*/}"
          git pull --all
          git checkout develop
          git merge main 

      - name: Authenticate GitHub CLI with PAT
        env:
          USER_PAT: ${{ secrets.USER_PAT }}
        run: |
          echo "${{ secrets.USER_PAT }}" | gh auth login --with-token
  
      - name: Create Pull Request from Main to Develop
        env:
          USER_PAT: ${{ secrets.USER_PAT }}
        run: |
          gh pr create --title "Daily Merge: Main into Develop" --body "This is an automated pull request to merge changes from main into develop." --head main --base develop
      
      - name: Approve Pull Request
        run: |
          gh pr review --approve --repo ${{ github.repository }} $(gh pr list --base develop --head main --limit 1 --json number --jq '.[0].number')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Push Changes
        run: |
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
